# Generated by Django 4.0.3 on 2022-04-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_roadmap_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadmap',
            old_name='owner',
            new_name='user',
        ),
    ]
