# Generated by Django 4.0.3 on 2022-04-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_owner_roadmap_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_url',
            field=models.URLField(max_length=300),
        ),
    ]
